-- PostgreSQL schema and seed script for local development.
-- Create the database first if needed:
--   createdb -h localhost -p 5432 -U postgres leave_management

DROP TABLE IF EXISTS "LeaveRequests";
DROP TABLE IF EXISTS "LeaveTypes";
DROP TABLE IF EXISTS "Employees";

CREATE TABLE "Employees" (
    "EmployeeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeCode" VARCHAR(20) NOT NULL UNIQUE,
    "FullName" VARCHAR(100) NOT NULL,
    "Email" VARCHAR(100) NOT NULL UNIQUE,
    "Department" VARCHAR(50) NOT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "LeaveTypes" (
    "LeaveTypeID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LeaveName" VARCHAR(50) NOT NULL
);

CREATE TABLE "LeaveRequests" (
    "RequestID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeID" INTEGER NOT NULL REFERENCES "Employees"("EmployeeID") ON DELETE RESTRICT,
    "LeaveTypeID" INTEGER NOT NULL REFERENCES "LeaveTypes"("LeaveTypeID") ON DELETE RESTRICT,
    "FromDate" DATE NOT NULL,
    "ToDate" DATE NOT NULL,
    "NumberOfDays" INTEGER NOT NULL,
    "Reason" VARCHAR(500) NOT NULL,
    "Status" VARCHAR(20) NOT NULL DEFAULT 'Pending',
    "CreatedDate" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ManagerComments" VARCHAR(500) NULL,
    CONSTRAINT "CK_LeaveRequests_Status" CHECK ("Status" IN ('Pending', 'Approved', 'Rejected')),
    CONSTRAINT "CK_LeaveRequests_DateRange" CHECK ("ToDate" >= "FromDate"),
    CONSTRAINT "CK_LeaveRequests_NumberOfDays" CHECK ("NumberOfDays" >= 1)
);

INSERT INTO "LeaveTypes" ("LeaveTypeID", "LeaveName")
OVERRIDING SYSTEM VALUE
VALUES (1, 'Annual Leave'), (2, 'Sick Leave'), (3, 'Unpaid Leave')
ON CONFLICT ("LeaveTypeID") DO NOTHING;
