-- Manual PostgreSQL schema for Employee Leave Management System.
-- EF Core migrations are the recommended way to create/update the database.

CREATE TABLE IF NOT EXISTS "Employees" (
    "EmployeeID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" varchar(50) NOT NULL,
    "LastName" varchar(50) NOT NULL,
    "Email" varchar(100) NOT NULL UNIQUE,
    "Department" varchar(50) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS "LeaveTypes" (
    "LeaveTypeID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LeaveName" varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "LeaveRequests" (
    "RequestID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeID" integer NOT NULL REFERENCES "Employees"("EmployeeID") ON DELETE RESTRICT,
    "LeaveTypeID" integer NOT NULL REFERENCES "LeaveTypes"("LeaveTypeID") ON DELETE RESTRICT,
    "FromDate" date NOT NULL,
    "ToDate" date NOT NULL,
    "NumberOfDays" integer NOT NULL,
    "Reason" varchar(500) NOT NULL,
    "Status" varchar(20) NOT NULL DEFAULT 'Pending',
    "ManagerComments" varchar(500),
    "CreatedDate" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_LeaveRequests_DateRange" CHECK ("ToDate" >= "FromDate"),
    CONSTRAINT "CK_LeaveRequests_Status" CHECK ("Status" IN ('Pending', 'Approved', 'Rejected'))
);

CREATE INDEX IF NOT EXISTS "IX_LeaveRequests_EmployeeID" ON "LeaveRequests" ("EmployeeID");
CREATE INDEX IF NOT EXISTS "IX_LeaveRequests_LeaveTypeID" ON "LeaveRequests" ("LeaveTypeID");

INSERT INTO "LeaveTypes" ("LeaveTypeID", "LeaveName") VALUES
    (1, 'Annual Leave'),
    (2, 'Sick Leave'),
    (3, 'Unpaid Leave')
ON CONFLICT ("LeaveTypeID") DO NOTHING;
